;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020352 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020352 COMAstra/COMAstraPickup_Action3: \"They're in good hands, Hancock. I've heard good things about you too. Mostly.\"")
EndFunction
