;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002006D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002006D MQAstraALT/MQAstraALT_ConcordApproach_Neg_P: \"I'm grabbing that power armor first.\"")
EndFunction
