;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002046A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002046A COMAstra/COMAstraBleedOut: \"Pinned and bleeding here. Anytime now!\"")
EndFunction
