;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200A4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200A4 MQAstraALT/MQAstraALT_NotNow_Pos_N: \"I'll be here. I'm not going anywhere. Haven't for a very long time.\"")
EndFunction
