;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002028C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002028C COMAstra/COMAstraInf_Ex4_NQue: \"I've turned it over every way I know how. It's love.\"")
EndFunction
