;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020247 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020247 COMAstra/COMAstraConf_Ex4_NQue: \"Ten years alone was... heavy. This is lighter. You make it lighter.\"")
EndFunction
