;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002014F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002014F MQAstraALT/MQAstraALT_InsideInstitute_Pos_N: \"You're right. Shaun first. Everything else -- the politics, the synths, the technology -- ...\"")
EndFunction
