;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020058 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020058 MQAstraALT/MQAstraALT_RedRocket_Pos_N: \"Museum of Freedom. A man named Preston Garvey and a handful of settlers are pinned down by...\"")
EndFunction
