;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002016E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002016E MQAstraALT/MQAstraALT_FathersTruth_Que_N: \"I don't know. I think so. No -- that's not honest. I'm shaken. I spent years trying to fin...\"")
EndFunction
