;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002006B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002006B MQAstraALT/MQAstraALT_ConcordApproach_Pos_N: \"Stay close. Room by room. Preston's people have held this long -- we just need to tip the ...\"")
EndFunction
