;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020295 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020295 COMAstra/COMAstraDis_Ex1_NPos: \"The way you've been acting -- I can't square it with the person I chose to follow.\"")
EndFunction
