;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002019B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002019B MQAstraALT/MQAstraALT_StagedGreeting: \"Concord's just south. Museum of Freedom. Preston's group is pinned down on the upper floor...\"")
EndFunction
