;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020188 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020188 MQAstraALT/MQAstraALT_Emergence_Pos_N: \"All the way. Now -- we need to be smart about what we share and with whom. The wrong word ...\"")
EndFunction
