;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204B8 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204B8 COMAstra/AstraAwarenessInteriorEntry: \"Unknown interior. Watch the doors; I will watch what is behind us.\"")
EndFunction
