;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002028A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002028A COMAstra/COMAstraInf_Ex3_NQue: \"It's real. What I feel for you is real.\"")
EndFunction
