;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020135 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020135 MQAstraALT/MQAstraALT_InstitutePrep_Que_N: \"Technology beyond anything left on the surface. Synths -- the real ones, not the rumors. A...\"")
EndFunction
