;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203C0 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203C0 COMAstra/COMAstraIdles: \"Nuka-World confirms a theory: marketing survives longer than governments.\"")
EndFunction
