;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002019A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002019A MQAstraALT/MQAstraALT_StagedGreeting: \"Red Rocket. One more thing before Concord.\"")
EndFunction
