;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201F1 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201F1 COMAstra/COMAstraFriend_Dialog7: \"You're not just an outcome. You're a choice.\"")
EndFunction
