;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002032F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002032F COMAstraTalk/COMAstraTalkGreetings: \"Hey you. I was hoping you'd come talk to me.\"")
EndFunction
