;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020194 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020194 MQAstraALT/MQAstraALT_Emergence_Que_N: \"That's between you and him. He's your son and he's the leader of the most powerful organiz...\"")
EndFunction
