;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202FF Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202FF MQAstraALT/MQAstraALT_StagedGreeting: \"Preston needs our help. Lives are in the balance — we should keep moving.\"")
EndFunction
