;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202BA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202BA COMAstra/COMAstra_09_RepeatDisdainToHatred_N: \"That's it. I'm past disappointed. Past angry. Done.\"")
EndFunction
