;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201D7 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201D7 COMAstra/COMAstraFriend_Ex3_PQue: \"Why don't you trust me?\"")
EndFunction
