;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020064 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020064 MQAstraALT/MQAstraALT_RedRocket_Que_N: \"Ten years of watching. Listening. Every patrol route, every radio frequency, every faction...\"")
EndFunction
