;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002040B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002040B COMAstraTalk/COMAstraTalk_StoryResponse: \"You know my story. Ask me again sometime anyway. It gets lighter every time I tell it.\"")
EndFunction
