;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200DD Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200DD MQAstraALT/MQAstraALT_FirstStepTerms_Pos_N: \"That's the way. In, solve the problem, out. No getting pulled into a campaign. Preston wil...\"")
EndFunction
