;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002017D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002017D MQAstraALT/MQAstraALT_TheChoice_Neu_N: \"I've asked myself that question every day since I walked out of Vault 98. What would I do ...\"")
EndFunction
