;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002019D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002019D MQAstraALT/MQAstraALT_StagedGreeting: \"We need to talk about Shaun. I have a lead on who took him.\"")
EndFunction
