;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020088 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020088 MQAstraALT/MQAstraALT_CoalitionPitch_Que_P: \"Why do you need me? You've had ten years.\"")
EndFunction
