;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202C8 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202C8 COMAstra/COMAstraInfRep_Reg_NNeg: \"Yeah. I was afraid of that.\"")
EndFunction
