;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002013E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002013E MQAstraALT/MQAstraALT_TheDescent_Neg_P: \"Save the sentiment for after we survive.\"")
EndFunction
