;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203BE Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203BE COMAstra/COMAstraIdles: \"Radiation is not a god. But this place makes a persuasive argument for fear.\"")
EndFunction
