;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200DF Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200DF MQAstraALT/MQAstraALT_FirstStepTerms_Neg_P: \"No. Shaun can't wait.\"")
EndFunction
