;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002011E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002011E MQAstraALT/MQAstraALT_DeaconEncounter_Neu_N: \"They rescue synths. Artificial people created by the Institute -- sentient beings who thin...\"")
EndFunction
