;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020086 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020086 MQAstraALT/MQAstraALT_CoalitionPitch_Neu_N: \"Minutemen protect settlements -- you just met them. The Railroad hides escaped synths. The...\"")
EndFunction
