;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020153 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020153 MQAstraALT/MQAstraALT_InsideInstitute_Neg_N: \"Yes. They did. And they'll have reasons -- good ones, probably. Survival, progress, the gr...\"")
EndFunction
