;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200E1 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200E1 MQAstraALT/MQAstraALT_FirstStepTerms_Neg_N: \"Then we move south now. Preston's capable -- he'll handle his own people. I just hope we d...\"")
EndFunction
