;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204C1 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204C1 COMAstra/AstraAwarenessLongInterior: \"Still tracking our route. We have not crossed our own trail yet.\"")
EndFunction
