;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020175 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020175 MQAstraALT/MQAstraALT_TheChoice_Pos_N: \"That's what I was hoping you'd say. It won't be easy. Every faction has a line they won't ...\"")
EndFunction
