;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002012B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002012B MQAstraALT/MQAstraALT_InstitutePrep_Neg_P: \"Save the nerves for later. Focus.\"")
EndFunction
