;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002006F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002006F MQAstraALT/MQAstraALT_ConcordApproach_Neg_N: \"Smart. Roof access is around the far side. Get the armor, get the minigun, and we clean ho...\"")
EndFunction
