;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002010F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002010F MQAstraALT/MQAstraALT_BoSContact_Que_N: \"The Brotherhood is tracking Institute relay signatures -- teleportation technology. They c...\"")
EndFunction
