;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200B9 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200B9 MQAstraALT/MQAstraALT_ConvergencePrep_Neg_P: \"You should have told me immediately.\"")
EndFunction
