;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002004F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002004F MQAstraALT/MQAstraALT_Sanctuary_Que_P: \"You said ten years. What happened to you?\"")
EndFunction
