;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002042F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002042F COMAstra/CA_Event_EnterPowerArmor_Astra: \"Big frame. Try not to step on me.\"")
EndFunction
