;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020159 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020159 MQAstraALT/MQAstraALT_InsideInstitute_Que_P: \"Can we trust anything they say?\"")
EndFunction
