;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002018A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002018A MQAstraALT/MQAstraALT_Emergence_Neg_P: \"Don't get sentimental. We still have work to do.\"")
EndFunction
