;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200FA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200FA MQAstraALT/MQAstraALT_CambridgeApproach_Que_P: \"Can we trust the Brotherhood?\"")
EndFunction
