;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200D2 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200D2 MQAstraALT/MQAstraALT_SanctuaryRegroup_Neu_N: \"Military order. Pre-war roots -- I understand that kind of thinking. They collect and cont...\"")
EndFunction
