;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002018C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002018C MQAstraALT/MQAstraALT_Emergence_Neg_N: \"You're right. Sentiment later, strategy now. Every faction is going to move when they lear...\"")
EndFunction
