;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002042B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002042B COMAstra/CA_Event_PickLock_Astra: \"Smooth. I'll pretend I didn't ask where you learned that.\"")
EndFunction
