;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020164 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020164 MQAstraALT/MQAstraALT_FathersTruth_Neg_P: \"You said you'd help me find him. You found him.\"")
EndFunction
