;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200F2 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200F2 MQAstraALT/MQAstraALT_CambridgeApproach_Neg_P: \"I don't want to get tangled up with soldiers.\"")
EndFunction
