;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002014D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002014D MQAstraALT/MQAstraALT_InsideInstitute_Pos_P: \"Focus. We need to find Shaun.\"")
EndFunction
