;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020414 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020414 COMAstra/CA_Event_RadDamage_Astra: \"Rads climbing. I didn't thaw out of one death to walk you into another.\"")
EndFunction
