;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203C6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203C6 COMAstra/COMAstraIdles: \"Nuka-Cola branding density is aggressive. I may need a filter.\"")
EndFunction
