;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204BE Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204BE COMAstra/AstraAwarenessLongInterior: \"We have been under this roof a while. Quiet does not mean empty.\"")
EndFunction
