;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002008F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002008F MQAstraALT/MQAstraALT_InfoFirst_Pos_P: \"I like that. Intelligence first, then contact.\"")
EndFunction
