;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002036C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002036C COMAstraTalk/COMAstraTalk_StatusResponse: \"I can't ignore this anymore. Something has to change.\"")
EndFunction
