;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020151 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020151 MQAstraALT/MQAstraALT_InsideInstitute_Neg_P: \"These people left everyone above to die.\"")
EndFunction
