;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020157 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020157 MQAstraALT/MQAstraALT_InsideInstitute_Neu_N: \"I know. Before the war, I worked for the DIA -- same government, same defense infrastructu...\"")
EndFunction
