;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202D7 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202D7 COMAstra/COMAstraMurder_N: \"You murdered someone who never raised a hand to you. We're done. Don't follow me.\"")
EndFunction
