;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020091 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020091 MQAstraALT/MQAstraALT_InfoFirst_Pos_N: \"Exactly. And our first stop is getting Preston's people settled. Once Sanctuary is secure,...\"")
EndFunction
