;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203DA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203DA COMAstra/COMAstraIdles: \"Nuka-Cola did not need an armed watershed. And yet.\"")
EndFunction
