;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020349 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020349 COMAstra/COMAstraPickup_Action3: \"You have my word, Codsworth. I'll bring them home in one piece.\"")
EndFunction
