;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002025C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002025C COMAstra/COMAstraInf_Ex2_NPos: \"To stay with you. Against every careful instinct I have. I choose you.\"")
EndFunction
