;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020286 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020286 COMAstra/COMAstraInf_Ex1_NQue: \"When you're gone, I don't sleep. I don't eat right. I finally know what depending on someo...\"")
EndFunction
