;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203CF Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203CF COMAstra/COMAstraIdles: \"Pre-war space fantasy, post-war murder automation. Efficient rebranding.\"")
EndFunction
