;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020371 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020371 COMAstraTalk/COMAstraTalk_StatusResponse: \"You're not just an outcome. You're a choice.\"")
EndFunction
