;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201A5 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201A5 MQAstraALT/MQAstraALT_StagedGreeting: \"Look at this place... I need to tell you what I'm seeing.\"")
EndFunction
