;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020181 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020181 MQAstraALT/MQAstraALT_TheChoice_Que_N: \"Honestly? I don't know. I spent ten years surviving alone. That's all I knew how to do. Th...\"")
EndFunction
