;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201AD Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201AD COMAstra/COMAstraFriend_Ex1_NPos: \"Curious. Most people don't choose the hard right.\"")
EndFunction
