;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203B3 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203B3 COMAstra/COMAstraIdles: \"Every condenser here feels like a lighthouse arguing with the dark.\"")
EndFunction
