;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020197 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020197 MQAstraALT/MQAstraALT_StagedGreeting: \"Stop — I need your help. There are people trapped in Concord. A man named Preston Garvey i...\"")
EndFunction
