;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002015B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002015B MQAstraALT/MQAstraALT_InsideInstitute_Que_N: \"Trust what you can verify. Question everything else. They've had decades to perfect the ar...\"")
EndFunction
