;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020118 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020118 MQAstraALT/MQAstraALT_DeaconEncounter_Neg_P: \"I don't like being followed.\"")
EndFunction
