;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200AA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200AA MQAstraALT/MQAstraALT_NotNow_Neu_P: \"What will you do while I'm gone?\"")
EndFunction
