;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002019F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002019F MQAstraALT/MQAstraALT_StagedGreeting: \"Preston's got a settlement that needs help. Quick word before we commit?\"")
EndFunction
