;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204B4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204B4 COMAstra/AstraAwarenessInteriorEntry: \"New interior. I will remember the way out. You remember why we came in.\"")
EndFunction
