;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020122 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020122 MQAstraALT/MQAstraALT_DeaconEncounter_Que_N: \"Because going in is only half the problem. Coming out -- with Shaun, with answers, without...\"")
EndFunction
