;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201A4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201A4 MQAstraALT/MQAstraALT_StagedGreeting: \"CIT ruins. This is it. Talk to me before we go under.\"")
EndFunction
