;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002012F Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002012F MQAstraALT/MQAstraALT_InstitutePrep_Neu_P: \"How do we actually get inside?\"")
EndFunction
