;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200BD Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200BD MQAstraALT/MQAstraALT_ConvergencePrep_Neu_P: \"The Institute? What is that?\"")
EndFunction
