;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002003A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002003A MQAstraALT/MQAstraALT_Bootstrap_Neu_N: \"I've been listening to every signal in this region for a very long time. The details can w...\"")
EndFunction
