;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020417 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020417 COMAstra/CA_Event_RadPoisoning_Astra: \"You're glowing the wrong way. Sit down, treat it, then we move.\"")
EndFunction
