;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200CA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200CA MQAstraALT/MQAstraALT_SanctuaryRegroup_Pos_N: \"They're soldiers. Disciplined, well-armed, and they know more about the Institute's techno...\"")
EndFunction
