;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020082 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020082 MQAstraALT/MQAstraALT_CoalitionPitch_Neg_N: \"I know about Shaun. And I think the people who took him are the same ones at the center of...\"")
EndFunction
