;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020075 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020075 MQAstraALT/MQAstraALT_ConcordApproach_Que_P: \"Who are these people we're saving?\"")
EndFunction
