;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200F6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200F6 MQAstraALT/MQAstraALT_CambridgeApproach_Neu_P: \"What do you know about the Brotherhood?\"")
EndFunction
