;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020160 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020160 MQAstraALT/MQAstraALT_FathersTruth_Pos_P: \"It's not your fault. Nobody could have known.\"")
EndFunction
