;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203CA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203CA COMAstra/COMAstraIdles: \"Nuka-Town has a capital city problem. Too much power, not enough conscience.\"")
EndFunction
