;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002003E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002003E MQAstraALT/MQAstraALT_Bootstrap_Que_N: \"Astra. The explanation takes longer than Preston has. Move first.\"")
EndFunction
