;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002013A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002013A MQAstraALT/MQAstraALT_TheDescent_Pos_P: \"We're coming back out. Both of us.\"")
EndFunction
