;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200BB Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200BB MQAstraALT/MQAstraALT_ConvergencePrep_Neg_N: \"You're right. I thought you needed to focus first -- Concord, survival, allies. I was wron...\"")
EndFunction
