;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002011C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002011C MQAstraALT/MQAstraALT_DeaconEncounter_Neu_P: \"What does the Railroad actually do?\"")
EndFunction
