;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200C1 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200C1 MQAstraALT/MQAstraALT_ConvergencePrep_Que_P: \"How do we find people that nobody can find?\"")
EndFunction
