;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002005C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002005C MQAstraALT/MQAstraALT_RedRocket_Neg_N: \"Good idea. That dog by the pumps looks like he could use a friend -- and there's some salv...\"")
EndFunction
