;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002013C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002013C MQAstraALT/MQAstraALT_TheDescent_Pos_N: \"Both of us. I'm holding you to that. Now -- the tunnel entrance should be in the sub-basem...\"")
EndFunction
