;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204C0 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204C0 COMAstra/AstraAwarenessLongInterior: \"We are deep enough in that the way back matters as much as the way forward.\"")
EndFunction
