;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020060 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020060 MQAstraALT/MQAstraALT_RedRocket_Neu_N: \"Concord's close. Raiders have been hitting a group of settlers holed up in the old museum....\"")
EndFunction
