;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020206 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020206 COMAstra/COMAstraAdm_Ex2_NPos: \"You're the only one I'd rearrange my life for.\"")
EndFunction
