;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203D7 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203D7 COMAstra/COMAstraIdles: \"Dry Rock Gulch is performing a western. The bullets are not theatrical.\"")
EndFunction
