;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020179 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020179 MQAstraALT/MQAstraALT_TheChoice_Neg_N: \"Maybe. But which ones? And who decides? That's the question that's torn the Commonwealth a...\"")
EndFunction
