;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201A3 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201A3 MQAstraALT/MQAstraALT_StagedGreeting: \"We have what we need. Minutemen, Brotherhood, Railroad. It's time to plan the Institute ap...\"")
EndFunction
