;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020416 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020416 COMAstra/CA_Event_RadPoisoning_Astra: \"That's rad poisoning. RadAway. Now. This isn't a negotiation.\"")
EndFunction
