;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002001C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002001C COMAstra/COMAstraDismiss_NNeg: \"I knew you couldn't bear to be without me.\"")
EndFunction
