;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202D0 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202D0 COMAstra/COMAstraInfRep_Reg_NQue: \"When I talked about my life before. I needed to know how it sounded.\"")
EndFunction
