;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020131 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020131 MQAstraALT/MQAstraALT_InstitutePrep_Neu_N: \"Three options. The Brotherhood is tracking relay signals -- teleportation. The Railroad ha...\"")
EndFunction
