;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203DC Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203DC COMAstra/COMAstraIdles: \"If the park wakes up all at once, I would prefer not to be inside the machinery.\"")
EndFunction
