;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020093 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020093 MQAstraALT/MQAstraALT_InfoFirst_Neg_P: \"That sounds like a lot of waiting around.\"")
EndFunction
