;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020190 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020190 MQAstraALT/MQAstraALT_Emergence_Neu_N: \"Preston is safest -- he'll support whatever you decide. The Railroad will want to know abo...\"")
EndFunction
