;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203AD Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203AD COMAstra/COMAstraIdles: \"If that iBot sent us here for ammunition, I hope it was feeling accurate.\"")
EndFunction
