;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020252 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020252 COMAstra/COMAstraInf_Ex1_NPos: \"My thoughts keep circling back to you. Every route I plan ends where you are.\"")
EndFunction
