;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002009D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002009D MQAstraALT/MQAstraALT_InfoFirst_Que_N: \"Then we walk into each conversation knowing more than they expect. That's how two vault dw...\"")
EndFunction
