;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020103 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020103 MQAstraALT/MQAstraALT_BoSContact_Pos_N: \"South. Toward CIT -- the old university campus. That's where the Institute used to be, bef...\"")
EndFunction
