;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200C3 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200C3 MQAstraALT/MQAstraALT_ConvergencePrep_Que_N: \"That's the question everyone out here asks. But I have leads. A place called Diamond City ...\"")
EndFunction
