;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020434 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020434 COMAstra/CA_Event_HealCompanion_Astra: \"I've stitched myself one-handed for years. Help is strange. Good strange.\"")
EndFunction
