;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204BB Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204BB COMAstra/AstraAwarenessReturnLocation: \"Familiar ground. That helps, right up until it makes us careless.\"")
EndFunction
