;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204B7 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204B7 COMAstra/AstraAwarenessInteriorEntry: \"I have not mapped this place yet. Stay close while I fix that.\"")
EndFunction
