;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002005E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002005E MQAstraALT/MQAstraALT_RedRocket_Neu_P: \"Tell me more about what's ahead.\"")
EndFunction
