;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203B9 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203B9 COMAstra/COMAstraIdles: \"Far Harbor is surviving on grit, condensers, and denial.\"")
EndFunction
