;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200EE Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200EE MQAstraALT/MQAstraALT_CambridgeApproach_Pos_P: \"Let's go help them.\"")
EndFunction
