;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020047 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020047 MQAstraALT/MQAstraALT_Sanctuary_Neg_P: \"I should help Codsworth first.\"")
EndFunction
