;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200A2 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200A2 MQAstraALT/MQAstraALT_NotNow_Pos_P: \"I'll come back when I'm ready.\"")
EndFunction
