;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020148 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020148 MQAstraALT/MQAstraALT_TheDescent_Que_N: \"I was a government analyst before the war. The DIA. If anyone in there has records of pre-...\"")
EndFunction
