;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020049 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020049 MQAstraALT/MQAstraALT_Sanctuary_Neg_N: \"Go. He's got bloatflies and worse out there. I'll be here when you're done.\"")
EndFunction
