;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020107 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020107 MQAstraALT/MQAstraALT_BoSContact_Neg_N: \"Neither do I. 'Destroy what you don't understand' isn't a philosophy -- it's fear with bet...\"")
EndFunction
