;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002019C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002019C MQAstraALT/MQAstraALT_StagedGreeting: \"Concord's done. Now I need to tell you what's really going on in this Commonwealth.\"")
EndFunction
