;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020116 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020116 MQAstraALT/MQAstraALT_DeaconEncounter_Pos_N: \"He'll want to test you first. The Railroad doesn't trust easily -- they can't afford to. B...\"")
EndFunction
