;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020073 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020073 MQAstraALT/MQAstraALT_ConcordApproach_Neu_N: \"Maybe a dozen raiders, scattered across two floors. They're not organized -- just aggressi...\"")
EndFunction
