;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002016A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002016A MQAstraALT/MQAstraALT_FathersTruth_Neu_N: \"It means your son controls the organization that every other faction wants to destroy. The...\"")
EndFunction
