;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020415 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020415 COMAstra/CA_Event_RadDamage_Astra: \"Radiation here. Keep it brief, or keep the RadAway handy.\"")
EndFunction
