;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201A2 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201A2 MQAstraALT/MQAstraALT_StagedGreeting: \"Did you see that man? Sunglasses, leather coat. He's been following us. We need to talk.\"")
EndFunction
