;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200CC Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200CC MQAstraALT/MQAstraALT_SanctuaryRegroup_Neg_P: \"Preston needs help with something first.\"")
EndFunction
