;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002034C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002034C COMAstra/COMAstraPickup_Action3: \"We'll try, MacCready. The not-getting-killed part, anyway.\"")
EndFunction
