;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200F4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200F4 MQAstraALT/MQAstraALT_CambridgeApproach_Neg_N: \"We don't have to join them. But showing up when someone's in trouble opens doors that knoc...\"")
EndFunction
