;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002010D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002010D MQAstraALT/MQAstraALT_BoSContact_Que_P: \"What did you learn from their transmissions?\"")
EndFunction
