;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203C4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203C4 COMAstra/COMAstraIdles: \"The old customer-service bots are still on duty. They're losing the argument with reality.\"")
EndFunction
