;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020166 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020166 MQAstraALT/MQAstraALT_FathersTruth_Neg_N: \"I did. I just didn't expect... this. He's not a prisoner. He's not a child. He's the most ...\"")
EndFunction
