;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202D2 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202D2 COMAstra/COMAstraInfRep_Reg_Dialog2: \"It's been a long time since I've had someone like you in my life.\"")
EndFunction
