;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020312 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020312 COMAstraTalk/COMAstraTalk_StatusResponse: \"The choices you've been making -- I can't stand behind them. We're drifting.\"")
EndFunction
