;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201C1 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201C1 COMAstra/COMAstraFriend_Ex2_NNeg: \"Then I'll keep earning it.\"")
EndFunction
