;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200F8 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200F8 MQAstraALT/MQAstraALT_CambridgeApproach_Neu_N: \"Disciplined. Ideological. They believe technology in the wrong hands ended the world -- an...\"")
EndFunction
