;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020245 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020245 COMAstra/COMAstraConf_Ex3_NQue: \"Nobody else has heard any of this. Only you.\"")
EndFunction
