;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201A7 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201A7 MQAstraALT/MQAstraALT_StagedGreeting: \"The factions are all going to want answers. We need to decide what we tell them.\"")
EndFunction
