;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204CA Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204CA COMAstra/AstraAwarenessCloseCall: \"You are hurt. The next room can wait long enough for a Stimpak.\"")
EndFunction
