;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020032 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020032 MQAstraALT/MQAstraALT_Bootstrap_Pos_N: \"Red Rocket's on the road south. We gear up there, then Concord.\"")
EndFunction
