;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002040C Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002040C COMAstraTalk/COMAstraTalk_StoryResponse: \"Still thinking about Vault 98? Me too. Less than I used to. That's your doing.\"")
EndFunction
