;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020051 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020051 MQAstraALT/MQAstraALT_Sanctuary_Que_N: \"Different vault. Different decade. I woke up alone and everyone else was dead. The rest ca...\"")
EndFunction
