;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200FC Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200FC MQAstraALT/MQAstraALT_CambridgeApproach_Que_N: \"Trust is a strong word. They want to destroy the Institute, which aligns with finding Shau...\"")
EndFunction
