;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200D6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200D6 MQAstraALT/MQAstraALT_SanctuaryRegroup_Que_N: \"He survived Quincy and led those people through hell to get here. Sanctuary is his now. An...\"")
EndFunction
