;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204C2 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204C2 COMAstra/AstraAwarenessLongInterior: \"This place keeps going. So do we, but we do it awake.\"")
EndFunction
