;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200A6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200A6 MQAstraALT/MQAstraALT_NotNow_Neg_P: \"Maybe I don't need your help at all.\"")
EndFunction
