;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203B6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203B6 COMAstra/COMAstraIdles: \"Trappers, fog crawlers, cultists. The ecosystem is aggressively opinionated.\"")
EndFunction
