;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200BF Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200BF MQAstraALT/MQAstraALT_ConvergencePrep_Neu_N: \"Nobody knows exactly. They operate underground -- literally. People vanish and replacement...\"")
EndFunction
