;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203BB Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203BB COMAstra/COMAstraIdles: \"Acadia's silence has structure. Someone taught these walls to keep secrets.\"")
EndFunction
