;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202B0 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202B0 COMAstra/COMAstra_07_RepeatAdmirationToNeutral_N: \"I don't recognize you anymore. We're back to square one.\"")
EndFunction
