;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200F0 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200F0 MQAstraALT/MQAstraALT_CambridgeApproach_Pos_N: \"Watch how Danse fights. The Brotherhood trains their soldiers well. And pay attention to w...\"")
EndFunction
