;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020084 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020084 MQAstraALT/MQAstraALT_CoalitionPitch_Neu_P: \"Tell me about these four factions.\"")
EndFunction
