;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203B4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203B4 COMAstra/COMAstraIdles: \"The Children of Atom talk like radiation is listening. I'm not convinced it isn't.\"")
EndFunction
