;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202FD Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202FD MQAstraALT/MQAstraALT_StagedGreeting: \"I left gear in that workbench — armor and ammo. Grab what you need before we head south.\"")
EndFunction
