;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020036 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020036 MQAstraALT/MQAstraALT_Bootstrap_Neg_N: \"Then I'm coming with you. But we can't wait long — every hour matters.\"")
EndFunction
