;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200E5 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200E5 MQAstraALT/MQAstraALT_FirstStepTerms_Neu_N: \"Settlers under threat. Could be raiders, could be something worse. Either way, it's a day'...\"")
EndFunction
