;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020177 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020177 MQAstraALT/MQAstraALT_TheChoice_Neg_P: \"Some of these factions deserve to fall.\"")
EndFunction
