;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204BD Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204BD COMAstra/AstraAwarenessReturnLocation: \"I know these walls. Let us see what moved while we were gone.\"")
EndFunction
