;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202B5 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202B5 COMAstra/COMAstra_08_RepeatNeutralToDisdain_N: \"Whatever we had is souring. I don't like who you're becoming.\"")
EndFunction
