;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020430 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020430 COMAstra/CA_Event_EnterPowerArmor_Astra: \"All that steel, and it still comes down to the person inside.\"")
EndFunction
