;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002012D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002012D MQAstraALT/MQAstraALT_InstitutePrep_Neg_N: \"You're right. It's just -- everything I've been working toward for ten years is under our ...\"")
EndFunction
