;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020173 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020173 MQAstraALT/MQAstraALT_TheChoice_Pos_P: \"We find a way that doesn't destroy everything.\"")
EndFunction
