;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200E3 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200E3 MQAstraALT/MQAstraALT_FirstStepTerms_Neu_P: \"How bad is it?\"")
EndFunction
