;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002011A Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002011A MQAstraALT/MQAstraALT_DeaconEncounter_Neg_N: \"Neither do I. But think about it -- they've been tracking Institute operations for years. ...\"")
EndFunction
