;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020095 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020095 MQAstraALT/MQAstraALT_InfoFirst_Neg_N: \"Not waiting. Preparing. The difference is whether you choose when to move or someone else ...\"")
EndFunction
