;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202FE Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202FE MQAstraALT/MQAstraALT_StagedGreeting: \"Ready? Red Rocket's our next stop — it's the staging point for Concord.\"")
EndFunction
