;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020105 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020105 MQAstraALT/MQAstraALT_BoSContact_Neg_P: \"I don't like how the Brotherhood thinks.\"")
EndFunction
