;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020146 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020146 MQAstraALT/MQAstraALT_TheDescent_Que_P: \"Are you afraid of what they'll think of you?\"")
EndFunction
