;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002010B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002010B MQAstraALT/MQAstraALT_BoSContact_Neu_N: \"Honest. Committed. The kind of soldier who follows orders because he believes in them, not...\"")
EndFunction
