;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002019E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002019E MQAstraALT/MQAstraALT_StagedGreeting: \"Preston's people are settling in. We should talk about our next move south.\"")
EndFunction
