;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020221 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020221 COMAstra/COMAstraConf_Ex1_NPos: \"Trust is complex. Our history says this is the right moment.\"")
EndFunction
