;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204B6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204B6 COMAstra/AstraAwarenessInteriorEntry: \"Different roof, same rule: know the exits before the shooting starts.\"")
EndFunction
