;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020056 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020056 MQAstraALT/MQAstraALT_RedRocket_Pos_P: \"Ready. What's in Concord?\"")
EndFunction
