;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020243 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020243 COMAstra/COMAstraConf_Ex2_NQue: \"Old wounds. Memories. Fears about who I'd become if I stayed alone much longer.\"")
EndFunction
