;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002004D Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002004D MQAstraALT/MQAstraALT_Sanctuary_Neu_N: \"Last Minuteman standing after the Quincy Massacre. He's got a handful of civilians — Sturg...\"")
EndFunction
