;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204BC Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204BC COMAstra/AstraAwarenessReturnLocation: \"Back again. I kept the exits filed where they belong.\"")
EndFunction
