;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002034B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002034B COMAstra/COMAstraPickup_Action3: \"Quiet keeps you alive, Cait. You should try it sometime.\"")
EndFunction
