;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203C1 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203C1 COMAstra/COMAstraIdles: \"This place was built to sell happiness by the gallon. Now it sells ammunition.\"")
EndFunction
