;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201A6 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201A6 MQAstraALT/MQAstraALT_StagedGreeting: \"I... we need to talk. About Father. About Shaun. Please.\"")
EndFunction
