;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020431 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020431 COMAstra/CA_Event_EnterPowerArmor_Astra: \"Power armor. The war's favorite costume.\"")
EndFunction
