;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200B0 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200B0 MQAstraALT/MQAstraALT_NotNow_Que_N: \"They always do. That's the one constant I've seen in ten years out here. But sometimes the...\"")
EndFunction
