;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204CC Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204CC COMAstra/AstraAwarenessCloseCall: \"Breathe. Reload. Heal. Then we decide what deserves us next.\"")
EndFunction
