;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200E9 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200E9 MQAstraALT/MQAstraALT_FirstStepTerms_Que_N: \"If I could? I'd help them. Ten years of watching people struggle alone... it changes you. ...\"")
EndFunction
