;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000203CC Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000203CC COMAstra/COMAstraIdles: \"The gangs here understand theater. Unfortunately, they also understand crossfire.\"")
EndFunction
