;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020077 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020077 MQAstraALT/MQAstraALT_ConcordApproach_Que_N: \"Preston Garvey -- last Minuteman standing after the Quincy Massacre. He's leading a handfu...\"")
EndFunction
