;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200CE Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200CE MQAstraALT/MQAstraALT_SanctuaryRegroup_Neg_N: \"Fair enough. We handle his first ask, keep it quick, then head south. Don't let side missi...\"")
EndFunction
