;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002022B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002022B COMAstra/COMAstraConf_Ex2_NPos: \"Things I've kept locked away. Memories. Ten years of fears I never said out loud.\"")
EndFunction
