;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000201B9 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000201B9 COMAstra/COMAstraFriend_Ex1_NQue: \"I'm mapping who you are. Not just what you do.\"")
EndFunction
