;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020080 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020080 MQAstraALT/MQAstraALT_CoalitionPitch_Neg_P: \"I don't care about factions. I need to find my son.\"")
EndFunction
