;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020101 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020101 MQAstraALT/MQAstraALT_BoSContact_Pos_P: \"He's a good man. What's our next move?\"")
EndFunction
