;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002028E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002028E COMAstra/COMAstraInf_Ex5_NQue: \"You're the reason I keep going. Everything else is just errands.\"")
EndFunction
