;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200A8 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200A8 MQAstraALT/MQAstraALT_NotNow_Neg_N: \"Maybe. But the wasteland has a way of changing minds. I'll still be here if it does.\"")
EndFunction
