;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000202AB Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000202AB COMAstra/COMAstra_06_RepeatInfatuationToAdmiration_N: \"I need some distance. My heart isn't safe with you right now.\"")
EndFunction
