;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204BF Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204BF COMAstra/AstraAwarenessLongInterior: \"Long interior. Check your ammunition before the next room checks it for you.\"")
EndFunction
