;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000204CB Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000204CB COMAstra/AstraAwarenessCloseCall: \"I nearly lost you there. Do not make me get used to that feeling.\"")
EndFunction
