;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020162 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020162 MQAstraALT/MQAstraALT_FathersTruth_Pos_N: \"Thank you. I've spent ten years collecting information and I missed the biggest piece. You...\"")
EndFunction
