;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020140 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020140 MQAstraALT/MQAstraALT_TheDescent_Neg_N: \"Fair enough. Eyes forward, then. West wing sub-basement. The tunnel entrance should be the...\"")
EndFunction
