;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020028 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020028 COMAstra/COMAstraGreetings: \"You're the one they call the Survivor. I'm Astra. Ready to move out?\"")
EndFunction
