;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002007E Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002007E MQAstraALT/MQAstraALT_CoalitionPitch_Pos_N: \"We make contact with each of them. Carefully. Learn what they want, what they're afraid of...\"")
EndFunction
