;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020120 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020120 MQAstraALT/MQAstraALT_DeaconEncounter_Que_P: \"Why do we need them if we're heading to the Institute anyway?\"")
EndFunction
