;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020129 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020129 MQAstraALT/MQAstraALT_InstitutePrep_Pos_N: \"Yes. We will. The CIT ruins are south of Cambridge -- that's where the Institute operated ...\"")
EndFunction
