;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020412 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020412 COMAstra/CA_Event_RadDamage_Astra: \"You're taking rads. Don't shrug at me. I've read your meter.\"")
EndFunction
