;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020045 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020045 MQAstraALT/MQAstraALT_Sanctuary_Pos_N: \"Stay close. I'll brief you on the way.\"")
EndFunction
