;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020114 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020114 MQAstraALT/MQAstraALT_DeaconEncounter_Pos_P: \"If they know a way into the Institute, I'm listening.\"")
EndFunction
