;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200DB Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200DB MQAstraALT/MQAstraALT_FirstStepTerms_Pos_P: \"Quick and clean. Then we head to Cambridge.\"")
EndFunction
