;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200D4 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200D4 MQAstraALT/MQAstraALT_SanctuaryRegroup_Que_P: \"Will Preston be okay without us?\"")
EndFunction
