;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_000200C8 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 000200C8 MQAstraALT/MQAstraALT_SanctuaryRegroup_Pos_P: \"Brotherhood of Steel? Let's check it out.\"")
EndFunction
