;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020266 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020266 COMAstra/COMAstraInf_Ex3_NPos: \"Feel? I spent ten years not letting myself. So yes. It's affection. And it scares me a lit...\"")
EndFunction
