;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020418 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020418 COMAstra/CA_Event_RadPoisoning_Astra: \"Rad sickness starts quiet and finishes loud. Please handle it.\"")
EndFunction
