;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_0002033B Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 0002033B COMAstraTalk/COMAstraTalk_NpcDismiss: \"All right. Let's talk about where I'll go.\"")
EndFunction
