;AUTO-GENERATED dialogue logger - regenerated by CompanionClaude Program.cs
Scriptname Fragments:TopicInfos:TIFL_00020413 Extends TopicInfo Hidden Const

Function Fragment_Begin(ObjectReference akSpeakerRef)
Debug.Trace("[ASTRADLG] 00020413 COMAstra/CA_Event_RadDamage_Astra: \"That crackle isn't ambiance. We're cooking. Move.\"")
EndFunction
